# Generated by Django 5.0.2 on 2024-03-01 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0002_alter_order_id_alter_orderitems_id_and_more'),
        ('product_api', '0010_productreview'),
        ('user_api', '0007_delete_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product_api.product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.customuser')),
            ],
        ),
    ]
