# Generated by Django 5.0.1 on 2024-02-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0005_remove_product_discount_remove_product_inventory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdiscount',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
