# Generated by Django 5.0.2 on 2024-02-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0007_alter_productdiscount_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productdiscount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productinventory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
