import { PrismaClient, UserRole } from "@prisma/client"

const prisma = new PrismaClient()

async function main() {
  const users = await prisma.user.createMany({
    data: [
      {
        id: "cltugibmc0000fws4nokichat",
        first_name: "Chelny",
        last_name: "Duplan",
        name: null,
        gender: "F",
        birth_date: "2000-06-22T00:00:00.000Z",
        email: "chelny@example.dev",
        emailVerified: "2024-03-16T19:04:23.120Z",
        password: "$2a$12$fH4X2hCQ2bGrPHElBcH7PuNglBFfwhEQSWQwwb1v2x8EkYwYzbVvK",
        image: null,
        role: UserRole.USER,
        two_factor_enabled: false,
        active: true,
      },
      {
        id: "cltugls4w0002fws46gsd6ysf",
        first_name: "Zayn",
        last_name: "Malik",
        name: null,
        gender: "M",
        birth_date: "1993-01-12T00:00:00.000Z",
        email: "zayn.malik@example.dev",
        emailVerified: "2024-03-16T19:07:02.289Z",
        password: "$2a$12$v7sJHa9.E5SGkGwdpWHytuiAfKbpX54H7SRc8uRuRCBUoFuHIeUsq",
        image: null,
        role: UserRole.USER,
        two_factor_enabled: false,
        active: true,
      },
    ],
    skipDuplicates: true,
  })

  const categories = await prisma.productCategory.createMany({
    data: [
      { id: "cltqh1sf2000008l40pqp40yb", name: "mens", description: "Men clothing" },
      { id: "cltqh22rz000108l4e1mq7ci6", name: "womens", description: "Women clothing" },
    ],
    skipDuplicates: true,
  })

  const products = await prisma.product.createMany({
    data: [
      {
        id: "ckm0jhvd800008dsdkc07do7m",
        brand: "Nike",
        name: "Epic Flex Running Shirt",
        description: "Premium running shirt with moisture-wicking technology for ultimate comfort.",
        sku: "RUN001",
        category_id: "cltqh1sf2000008l40pqp40yb",
        colors: "Black;Blue",
        price: 79.99,
      },
      {
        id: "ckm0jhvd900018dsdkr0bsiu9",
        brand: "Adidas",
        name: "UltraBoost Performance Shorts",
        description: "Stay cool and stylish during your workouts with these high-performance shorts.",
        sku: "SHORT002",
        category_id: "cltqh22rz000108l4e1mq7ci6",
        colors: "Gray;Red",
        price: 55.99,
      },
      {
        id: "ckm0jhvda00028dsdkqg6n4hk",
        brand: "Under Armour",
        name: "HeatGear Compression Leggings",
        description: "Compression leggings designed to provide maximum support and flexibility for intense workouts.",
        sku: "LEGG003",
        category_id: "cltqh1sf2000008l40pqp40yb",
        colors: "Black;Green",
        price: 92.99,
      },
      {
        id: "ckm0jhvdg00038dsdkl9dbz7x",
        brand: "Puma",
        name: "Ignite Running Shoes",
        description: "Experience the ultimate comfort and energy return with these high-performance running shoes.",
        sku: "SHOES004",
        category_id: "cltqh22rz000108l4e1mq7ci6",
        colors: "Blue;Yellow",
        price: 69.99,
      },
      {
        id: "ckm0jhvdh00048dsdklqp3ps4",
        brand: "Adidas",
        name: "Classic Track Jacket",
        description: "Timeless design meets modern comfort in this classic track jacket.",
        sku: "JACKET005",
        category_id: "cltqh1sf2000008l40pqp40yb",
        colors: "Red;White",
        price: 88.99,
      },
      {
        id: "ckm0jhvdi00058dsdkp1fbqym",
        brand: "Nike",
        name: "Pro Hypercool Training Shorts",
        description: "Push your limits with these advanced training shorts featuring Hypercool technology.",
        sku: "SHORT006",
        category_id: "cltqh22rz000108l4e1mq7ci6",
        colors: "Black;Gray",
        price: 76.99,
      },
      {
        id: "ckm0jhvdj00068dsdkthb8tmn",
        brand: "Under Armour",
        name: "Charged Bandit 6 Running Shoes",
        description: "Responsive cushioning and a comfortable fit make these running shoes a top choice.",
        sku: "SHOES007",
        category_id: "cltqh1sf2000008l40pqp40yb",
        colors: "Blue;White",
        price: 97.99,
      },
      {
        id: "ckm0jhvdk00078dsdkksvhzsz",
        brand: "Puma",
        name: "Essentials Hooded Sweatshirt",
        description: "Stay warm and stylish in this essentials hooded sweatshirt from Puma.",
        sku: "HOODIE008",
        category_id: "cltqh22rz000108l4e1mq7ci6",
        colors: "Gray;Black",
        price: 45.99,
      },
      {
        id: "ckm0jhvdl00088dsdkb4hd4ix",
        brand: "Nike",
        name: "Tech Fleece Joggers",
        description: "Upgrade your athleisure wardrobe with these comfortable and stylish Tech Fleece joggers.",
        sku: "JOGGER009",
        category_id: "cltqh1sf2000008l40pqp40yb",
        colors: "Black;Blue",
        price: 68.99,
      },
      {
        id: "ckm0jhvdm00098dsdkvlcd5wo",
        brand: "Adidas",
        name: "Superstar Originals Sneakers",
        description: "Iconic Superstar sneakers combining classic style with modern comfort.",
        sku: "SNEAKERS010",
        category_id: "cltqh22rz000108l4e1mq7ci6",
        colors: "White;Black",
        price: 59.99,
      },
      {
        id: "ckm0jhvdn00108dsdkouujc27",
        brand: "Nike",
        name: "Dri-FIT Performance T-Shirt",
        description: "Experience the power of Dri-FIT technology in this performance T-shirt for intense workouts.",
        sku: "TSHIRT011",
        category_id: "cltqh1sf2000008l40pqp40yb",
        colors: "Gray",
        price: 49.99,
      },
      {
        id: "ckm0jhvdo00118dsdkw5lp5yn",
        brand: "Puma",
        name: "Retro Track Pants",
        description: "Relive the retro vibes with these comfortable and stylish track pants from Puma.",
        sku: "TRACKPANTS012",
        category_id: "cltqh22rz000108l4e1mq7ci6",
        colors: "Blue",
        price: 79.99,
      },
      {
        id: "ckm0jhvdp00128dsdkjwmmjaz",
        brand: "Under Armour",
        name: "UA Tech Hoodie",
        description: "Stay warm and dry in style with this UA Tech Hoodie featuring moisture-wicking technology.",
        sku: "UAHOODIE013",
        category_id: "cltqh1sf2000008l40pqp40yb",
        colors: "Red",
        price: 89.99,
      },
      {
        id: "ckm0jhvdq00138dsdkzv9t0b2",
        brand: "Adidas",
        name: "Essentials Backpack",
        description: "Carry your essentials in style with this durable and sleek backpack from Adidas.",
        sku: "BACKPACK014",
        category_id: "cltqh22rz000108l4e1mq7ci6",
        colors: "Black",
        price: 45.99,
      },
      {
        id: "ckm0jhvdr00148dsdk68vxotv",
        brand: "Nike",
        name: "Air Max 270 Sneakers",
        description: "Step into the future with the iconic Air Max 270 sneakers, offering comfort and style.",
        sku: "AIRMAX270015",
        category_id: "cltqh1sf2000008l40pqp40yb",
        colors: "White",
        price: 99.99,
      },
      {
        id: "ckm0jhvds00158dsdk52wh1t8",
        brand: "Under Armour",
        name: "ArmourVent Cap",
        description: "Stay cool and protected with the ArmourVent technology in this stylish cap from Under Armour.",
        sku: "CAP016",
        category_id: "cltqh22rz000108l4e1mq7ci6",
        colors: "Blue",
        price: 47.99,
      },
      {
        id: "ckm0jhvdt00168dsdkfbre3h1",
        brand: "Adidas",
        name: "Ultimate High-Performance Socks",
        description: "Maximize your comfort with these ultimate high-performance socks from Adidas.",
        sku: "SOCKS017",
        category_id: "cltqh1sf2000008l40pqp40yb",
        colors: "Black",
        price: 48.99,
      },
      {
        id: "ckm0jhvdu00178dsdkd9tkjxg",
        brand: "Nike",
        name: "Legend React Running Shoes",
        description: "Achieve legendary runs with the comfort and performance of Legend React running shoes.",
        sku: "REACTSHOES018",
        category_id: "cltqh22rz000108l4e1mq7ci6",
        colors: "Gray",
        price: 65.99,
      },
      {
        id: "ckm0jhvdv00188dsdkmh9dh99",
        brand: "Puma",
        name: "Enzo Sport Sneakers",
        description: "Elevate your style and performance with these Enzo Sport sneakers from Puma.",
        sku: "ENZOSNEAKERS019",
        category_id: "cltqh1sf2000008l40pqp40yb",
        colors: "Red",
        price: 74.99,
      },
      {
        id: "ckm0jhvdw00198dsdk8we6ifd",
        brand: "Under Armour",
        name: "ColdGear Infrared Gloves",
        description: "Stay warm in cold weather with these ColdGear Infrared gloves from Under Armour.",
        sku: "GLOVES020",
        category_id: "cltqh22rz000108l4e1mq7ci6",
        colors: "Black",
        price: 55.99,
      },
      {
        id: "ckm0jhvdx00208dsdkatncxg1",
        brand: "Adidas",
        name: "Alphabounce Beyond Running Shoes",
        description: "Experience the ultimate bounce and comfort with Alphabounce Beyond running shoes.",
        sku: "ALPHABOUNCE021",
        category_id: "cltqh1sf2000008l40pqp40yb",
        colors: "White",
        price: 79.98,
      },
      {
        id: "ckm0jhvdy00218dsdkwq6h4u5",
        brand: "Nike",
        name: "Sportswear Club Fleece Hoodie",
        description: "Join the club of comfort and style with this Sportswear Club Fleece Hoodie from Nike.",
        sku: "FLEECEHOODIE022",
        category_id: "cltqh22rz000108l4e1mq7ci6",
        colors: "Blue",
        price: 68.99,
      },
      {
        id: "ckm0jhvdz00228dsdkfnhzp7o",
        brand: "Under Armour",
        name: "Rush Compression Tights",
        description: "Enhance your performance with the innovative Rush Compression Tights from Under Armour.",
        sku: "COMPRESSIONTIGHTS023",
        category_id: "cltqh1sf2000008l40pqp40yb",
        colors: "Gray",
        price: 95.99,
      },
      {
        id: "ckm0jhw0000018dsdkpjkskeo",
        brand: "Puma",
        name: "Classics T7 Track Jacket",
        description: "Step into classic style with the timeless T7 Track Jacket from Puma.",
        sku: "TRACKJACKET024",
        category_id: "cltqh1sf2000008l40pqp40yb",
        colors: "Red",
        price: 79.99,
      },
      {
        id: "ckm0jhw0000028dsdkqn95eal",
        brand: "Reebok",
        name: "CrossFit Powerlifting Belt",
        description: "Heavy-duty powerlifting belt for optimal support during your CrossFit workouts.",
        sku: "BELT025",
        category_id: "cltqh22rz000108l4e1mq7ci6",
        colors: "Black;Red",
        price: 79.99,
      },
    ],
    skipDuplicates: true,
  })

  const inventory = await prisma.productInventory.createMany({
    data: [
      { id: "cku2a1bzg0000fl5q3i5q5wem", product_id: "ckm0jhvd800008dsdkc07do7m", quantity: 2 },
      { id: "cku2a1c080000gl5q0tyo1dl1", product_id: "ckm0jhvd900018dsdkr0bsiu9", quantity: 1 },
      { id: "cku2a1c5i0000hl5qc8yuk96y", product_id: "ckm0jhvda00028dsdkqg6n4hk", quantity: 30 },
      { id: "cku2a1caf0000il5q20l3mdyw", product_id: "ckm0jhvdg00038dsdkl9dbz7x", quantity: 30 },
      { id: "cku2a1cfg0000jl5q1i82t6f3", product_id: "ckm0jhvdh00048dsdklqp3ps4", quantity: 30 },
      { id: "cku2a1cn90000kl5q2sx40yrt", product_id: "ckm0jhvdi00058dsdkp1fbqym", quantity: 0 },
      { id: "cku2a1cw80000ll5q9ekq1ksh", product_id: "ckm0jhvdj00068dsdkthb8tmn", quantity: 30 },
      { id: "cku2a1d3q0000ml5q8fq61b3b", product_id: "ckm0jhvdk00078dsdkksvhzsz", quantity: 30 },
      { id: "cku2a1daf0000nl5qdfb7a80l", product_id: "ckm0jhvdl00088dsdkb4hd4ix", quantity: 30 },
      { id: "cku2a1dgg0000ol5q4i4fw9mk", product_id: "ckm0jhvdm00098dsdkvlcd5wo", quantity: 30 },
      { id: "cku2a1drq0000pl5q5ne2xrv7", product_id: "ckm0jhvdn00108dsdkouujc27", quantity: 30 },
      { id: "cku2a1dzy0000ql5q3k85ksd8", product_id: "ckm0jhvdo00118dsdkw5lp5yn", quantity: 30 },
      { id: "cku2a1e7v0000rl5q5yxtmp6i", product_id: "ckm0jhvdp00128dsdkjwmmjaz", quantity: 30 },
      { id: "cku2a1ef40000sl5qdnco87ts", product_id: "ckm0jhvdq00138dsdkzv9t0b2", quantity: 30 },
      { id: "cku2a1enm0000tl5q7zvd0v9e", product_id: "ckm0jhvdr00148dsdk68vxotv", quantity: 30 },
      { id: "cku2a1ewm0000ul5q8fz1ujic", product_id: "ckm0jhvds00158dsdk52wh1t8", quantity: 30 },
      { id: "cku2a1f4t0000vl5q6t48dq3g", product_id: "ckm0jhvdt00168dsdkfbre3h1", quantity: 30 },
      { id: "cku2a1fb60000wl5q9wiz5aou", product_id: "ckm0jhvdu00178dsdkd9tkjxg", quantity: 30 },
      { id: "cku2a1fjv0000xl5qbxwgy2bp", product_id: "ckm0jhvdv00188dsdkmh9dh99", quantity: 30 },
      { id: "cku2a1fr80000yl5q17bya25e", product_id: "ckm0jhvdw00198dsdk8we6ifd", quantity: 30 },
      { id: "cku2a1g7200000al5qjv6md88", product_id: "ckm0jhvdx00208dsdkatncxg1", quantity: 30 },
      { id: "cku2a1ggs0000bl5qf6stj9zv", product_id: "ckm0jhvdy00218dsdkwq6h4u5", quantity: 30 },
      { id: "cku2a1gs00000cl5qc3pxek3y", product_id: "ckm0jhvdz00228dsdkfnhzp7o", quantity: 30 },
      { id: "cku2a1gyi0000dl5q0dp9doo0", product_id: "ckm0jhw0000018dsdkpjkskeo", quantity: 30 },
      { id: "cku2a1h6j0000el5qam1p25mn", product_id: "ckm0jhw0000028dsdkqn95eal", quantity: 30 },
    ],
    skipDuplicates: true,
  })

  const discounts = await prisma.productDiscount.createMany({
    data: [
      {
        id: "cli0jhvdx00208dsdkatncxg1",
        product_id: "ckm0jhvda00028dsdkqg6n4hk",
        name: "Discount for HeatGear Compression Leggings",
        description: "Special discount for HeatGear Compression Leggings. Limited time offer!",
        discount_percent: 0.1,
        active: true,
      },
      {
        id: "cli0jhvdy00218dsdkwq6h4u5",
        product_id: "ckm0jhvd900018dsdkr0bsiu9",
        name: "Discount for UltraBoost Performance Shorts",
        description: "Special discount for UltraBoost Performance Shorts. Limited time offer!",
        discount_percent: 0.1,
        active: true,
      },
      {
        id: "cli0jhvdw00198dsdk8we6ifd",
        product_id: "ckm0jhvdv00188dsdkmh9dh99",
        name: "Discount for Enzo Sport Sneakers",
        description: "Special discount for Enzo Sport Sneakers. Limited time offer!",
        discount_percent: 0.1,
        active: true,
      },
      {
        id: "cli0jhvdt00168dsdkfbre3h1",
        product_id: "ckm0jhvdt00168dsdkfbre3h1",
        name: "Discount for Ultimate High-Performance Socks",
        description: "Special discount for Ultimate High-Performance Socks. Limited time offer!",
        discount_percent: 0.1,
        active: true,
      },
      {
        id: "cli0jhvdi00058dsdkp1fbqym",
        product_id: "ckm0jhvdi00058dsdkp1fbqym",
        name: "Discount for Pro Hypercool Training Shorts",
        description: "Special discount for Pro Hypercool Training Shorts. Limited time offer!",
        discount_percent: 0.1,
        active: true,
      },
      {
        id: "cli0jhvdu00178dsdkd9tkjxg",
        product_id: "ckm0jhvdu00178dsdkd9tkjxg",
        name: "Discount for Legend React Running Shoes",
        description: "Special discount for Legend React Running Shoes. Limited time offer!",
        discount_percent: 0.1,
        active: true,
      },
      {
        id: "cli0jhvdn00108dsdkouujc27",
        product_id: "ckm0jhvdn00108dsdkouujc27",
        name: "Discount for Dri-FIT Performance T-Shirt",
        description: "Special discount for Dri-FIT Performance T-Shirt. Limited time offer!",
        discount_percent: 0.1,
        active: true,
      },
      {
        id: "cli0jhvdm00098dsdkvlcd5wo",
        product_id: "ckm0jhvdm00098dsdkvlcd5wo",
        name: "Discount for Superstar Originals Sneakers",
        description: "Special discount for Superstar Originals Sneakers. Limited time offer!",
        discount_percent: 0.1,
        active: true,
      },
      {
        id: "cli0jhvdp00128dsdkjwmmjaz",
        product_id: "ckm0jhvdp00128dsdkjwmmjaz",
        name: "Discount for UA Tech Hoodie",
        description: "Special discount for UA Tech Hoodie. Limited time offer!",
        discount_percent: 0.1,
        active: true,
      },
      {
        id: "cli0jhvdj00068dsdkthb8tmn",
        product_id: "ckm0jhvdj00068dsdkthb8tmn",
        name: "Discount for Charged Bandit 6 Running Shoes",
        description: "Special discount for Charged Bandit 6 Running Shoes. Limited time offer!",
        discount_percent: 0.1,
        active: true,
      },
    ],
    skipDuplicates: true,
  })

  const reviews = await prisma.productReview.createMany({
    data: [
      {
        id: "cltuikfe0000108l42qst7acq",
        user_id: "cltugibmc0000fws4nokichat",
        product_id: "ckm0jhvd800008dsdkc07do7m",
        rating: 3,
        title: "Okay shirt",
        comment: "The shirt is a little too wide for me.",
      },
      {
        id: "cltuijmap000008l486ohcopv",
        user_id: "cltugibmc0000fws4nokichat",
        product_id: "ckm0jhvda00028dsdkqg6n4hk",
        rating: 5,
        title: "I like it like that!",
        comment: "The shirt is made with good fabric! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam porta molestie tortor ut ultricies. Aliquam in sagittis tortor. Integer fringilla commodo lacus ac fermentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris imperdiet posuere diam, a fringilla elit viverra eget. Nullam at risus molestie nulla bibendum dignissim. Nullam ullamcorper bibendum odio et interdum. Nulla porta ultrices aliquam. Aenean bibendum placerat mi, a ornare nunc bibendum non.",
      },
      {
        id: "cltuiklf2000208l47iusfj69",
        user_id: "cltugls4w0002fws46gsd6ysf",
        product_id: "ckm0jhvd900018dsdkr0bsiu9",
        rating: 4,
        title: "Almost perfect but...",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam porta molestie tortor ut ultricies. Aliquam in sagittis tortor. Integer fringilla commodo lacus ac fermentum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris imperdiet posuere diam, a fringilla elit viverra eget. Nullam at risus molestie nulla bibendum dignissim. Nullam ullamcorper bibendum odio et interdum. Nulla porta ultrices aliquam. Aenean bibendum placerat mi, a ornare nunc bibendum non.",
      },
      {
        id: "cltuikq9l000308l4e4fzht4y",
        user_id: "cltugibmc0000fws4nokichat",
        product_id: "ckm0jhvd900018dsdkr0bsiu9",
        rating: 1,
        title: "Meh...",
        comment: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam porta molestie tortor ut ultricies. Aliquam in sagittis tortor. Integer fringilla commodo lacus ac fermentum.",
      },
    ],
    skipDuplicates: true,
  })

  console.log({ users, categories, products, inventory, discounts, reviews })
}

main()
  .then(async () => {
    await prisma.$disconnect()
  })
  .catch(async (e) => {
    console.error(e)
    await prisma.$disconnect()
    process.exit(1)
  })